name: Test jinad

on:
  pull_request:
    branches:
      - master

jobs:
  jinad-test:
    if: |
      !startsWith(github.event.head_commit.message, 'chore') &&
      !startsWith(github.event.head_commit.message, 'build: hotfix') &&
      !endsWith(github.event.head_commit.message, 'reformatted by jina-dev-bot')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build jina test-pip with fluentd
        run: |
          docker build -f tests/integration/jinad/Dockerfiles/Dockerfile -t jinaai/jina:test-pip .
          docker build --build-arg PIP_TAG="[devel]" -f tests/integration/jinad/Dockerfiles/Dockerfile -t jinaai/jina:test-pip .
      - name: Build hub pod image
        run: |
          pip install .[cicd] --no-cache-dir
          jina hub build --prune-images --raise-error --host-info --test-uses --daemon tests/intagration/jinad/hub_mwu
          # change the tag to latest to make it independent of jina version.
          IMAGE_ID=$(docker images --filter=reference='jinahub/pod.encoder.dummy_mwu_encoder' --format "{{.ID}}")
          docker tag $IMAGE_ID jinahub/pod.encoder.dummy_mwu_encoder:latest
      - name: Test jinad
        run: |
          ./tests/integration/jinad/exec_tests.sh
        timeout-minutes: 30
        env:
          JINAHUB_USERNAME: ${{ secrets.JINAHUB_USERNAME }}
          JINAHUB_PASSWORD: ${{ secrets.JINAHUB_PASSWORD }}